openapi: 3.0.3
info:
  title: Let's Play API
  description: |
    RESTful CRUD API for a small e-commerce-like platform.
    Manages users and products with JWT-based authentication and role-based access control.
    - **Admin**: manage all users and products
    - **User**: manage only their own products
    Identifiers for users and products are **MongoDB ObjectIds** (24-character hex strings).
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development

tags:
  - name: Auth
    description: Registration and login
  - name: Users
    description: User management
  - name: Products
    description: Product catalog and management

paths:
  /auth/signup:
    post:
      tags: [Auth]
      summary: Sign up
      description: |
        Creates a new user with role **USER**. Password is hashed with BCrypt before storage.
        Admin users are not created via signup; they are defined internally or created by another admin via POST /users.
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request (e.g. validation failure)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/signin:
    post:
      tags: [Auth]
      summary: Sign in
      description: |
        **Success**: returns 200 with a JWT in the response body. Client must send this token in the **Authorization** header as `Bearer <token>` on subsequent requests. Using the header (not a cookie) is the standard for APIs and avoids CSRF and cross-origin cookie issues.
        **Failure**: returns 401 with the standard error body (e.g. invalid email or password).
      operationId: signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
      responses:
        '200':
          description: Sign-in successful; use the returned token in Authorization header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      tags: [Users]
      summary: List all users
      description: Admin only. Returns all users (passwords never included).
      operationId: listUsers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      tags: [Users]
      summary: Create a user
      description: Admin only. Creates a new user (e.g. for provisioning).
      operationId: createUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{id}:
    parameters:
      - $ref: '#/components/parameters/UserId'
    get:
      tags: [Users]
      summary: Get user by ID
      description: Admin or self only.
      operationId: getUserById
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags: [Users]
      summary: Update user
      description: Admin or self only.
      operationId: updateUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          description: Email already in use
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags: [Users]
      summary: Delete user
      description: Admin only.
      operationId: deleteUser
      security:
        - bearerAuth: []
      responses:
        '204':
          description: User deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /products:
    get:
      tags: [Products]
      summary: List all products
      description: Public access. No authentication required.
      operationId: listProducts
      parameters:
        - name: userId
          in: query
          description: Filter by owner user ID (MongoDB ObjectId, optional)
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
        - name: page
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Paginated list of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'

    post:
      tags: [Products]
      summary: Create a product
      description: Authenticated users only. The product is owned by the current user.
      operationId: createProduct
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /products/{id}:
    parameters:
      - $ref: '#/components/parameters/ProductId'
    get:
      tags: [Products]
      summary: Get product by ID
      description: Public access.
      operationId: getProductById
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags: [Products]
      summary: Update product
      description: Product owner or admin only.
      operationId: updateProduct
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [Products]
      summary: Delete product
      description: Product owner or admin only.
      operationId: deleteProduct
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Product deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT obtained from POST /auth/signin. Send in Authorization header as Bearer <token> (not in a cookie).

  parameters:
    UserId:
      name: id
      in: path
      required: true
      description: User ID (MongoDB ObjectId, 24 hex characters)
      schema:
        type: string
        pattern: '^[a-fA-F0-9]{24}$'
    ProductId:
      name: id
      in: path
      required: true
      description: Product ID (MongoDB ObjectId, 24 hex characters)
      schema:
        type: string
        pattern: '^[a-fA-F0-9]{24}$'

  responses:
    Unauthorized:
      description: Missing or invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Unauthorized
            status: 401
    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Forbidden
            status: 403
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Not found
            status: 404
    BadRequest:
      description: Invalid request (validation or business rule)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Validation failed
            status: 400
    Conflict:
      description: Conflict (e.g. duplicate email)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Email already registered
            status: 409

  schemas:
    User:
      type: object
      description: User representation (password never included in responses)
      properties:
        id:
          type: string
          description: Unique identifier (MongoDB ObjectId)
          pattern: '^[a-fA-F0-9]{24}$'
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [USER, ADMIN]
      required: [id, name, email, role]

    SignupRequest:
      type: object
      description: Signup always creates a user with role USER. No role field.
      properties:
        name:
          type: string
          minLength: 1
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 1
      required: [name, email, password]

    UserCreate:
      type: object
      description: Used by admin only (POST /users). May set role USER or ADMIN.
      properties:
        name:
          type: string
          minLength: 1
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 1
        role:
          type: string
          enum: [USER, ADMIN]
      required: [name, email, password, role]

    UserUpdate:
      type: object
      description: At least one field must be provided for PUT /users/{id}.
      properties:
        name:
          type: string
          minLength: 1
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 1
        role:
          type: string
          enum: [USER, ADMIN]

    Products:
      type: object
      description: Paginated response for GET /products.
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Product'
          description: Products on this page
        totalElements:
          type: integer
          minimum: 0
          description: Total number of products across all pages
        totalPages:
          type: integer
          minimum: 0
          description: Total number of pages
        size:
          type: integer
          minimum: 1
          description: Page size (same as query param)
        number:
          type: integer
          minimum: 0
          description: Zero-based page index (same as query param)
      required: [content, totalElements, totalPages, size, number]

    Product:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier (MongoDB ObjectId)
          pattern: '^[a-fA-F0-9]{24}$'
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
          minimum: 0
        quantity:
          type: integer
          minimum: 0
        userId:
          type: string
          description: ID of the user who owns this product (MongoDB ObjectId)
          pattern: '^[a-fA-F0-9]{24}$'
      required: [id, name, price, quantity, userId]

    ProductCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
        price:
          type: number
          format: double
          minimum: 0
        quantity:
          type: integer
          minimum: 0
      required: [name, price, quantity]

    ProductUpdate:
      type: object
      description: At least one field must be provided for PUT /products/{id}.
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
        price:
          type: number
          format: double
          minimum: 0
        quantity:
          type: integer
          minimum: 0

    SigninRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required: [email, password]

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT to send in Authorization header as Bearer {token}
        type:
          type: string
          example: Bearer
      required: [token]

    Error:
      type: object
      description: |
        Standard error response for all error responses (4xx). Use consistently across the API.
        Only message and status are included; the request path is already known by the client.
      properties:
        message:
          type: string
          description: Human-readable error message
        status:
          type: integer
          description: HTTP status code (matches the response status)
      required: [message, status]
